// Generated by CoffeeScript 1.6.2
(function() {
  var Game, Level, Sprite, canvas, game;

  Sprite = (function() {
    function Sprite(image, left, top, width, height) {
      this.image = image;
      this.left = left;
      this.top = top;
      this.width = width;
      this.height = height;
    }

    return Sprite;

  })();

  Level = (function() {
    Level.prototype.entities = null;

    Level.prototype.background = null;

    function Level(filename) {
      $.get(filename, function(data) {});
    }

    return Level;

  })();

  Game = (function() {
    Game.prototype.WIDTH = 350;

    Game.prototype.HEIGHT = 500;

    Game.prototype.FPS = 30;

    Game.prototype.interval = null;

    function Game(canvas) {
      this.canvas = canvas;
      this.setup();
    }

    Game.prototype.setup = function() {
      this.canvas.height = this.HEIGHT;
      return this.canvas.width = this.WIDTH;
    };

    Game.prototype.start = function() {
      var _this = this;

      return this.interval = setInterval(function() {
        _this.update();
        return _this.draw();
      }, 1000 / this.FPS);
    };

    Game.prototype.update = function() {};

    Game.prototype.draw = function() {
      var ctx;

      ctx = canvas.getContext('2d');
      ctx.fillStyle = '#000';
      return ctx.fillRect(0, 0, this.WIDTH, this.HEIGHT);
    };

    return Game;

  })();

  canvas = document.getElementById('canvas');

  game = new Game(canvas);

  game.start();

}).call(this);
